apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prophet-collector.fullname" . }}
  labels:
    {{- include "prophet-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  org-token: {{ required "orgToken is required" .Values.orgToken | quote }}
